FROM node:22 

WORKDIR /app

COPY package.* ./
RUN npm i -g corepack@latest && corepack enable
COPY packages/backend/package.json ./packages/backend/package.json
COPY packages/backend/prisma/schema.prisma ./packages/backend/prisma/schema.prisma
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

ENV NODE_OPTIONS=--max_old_space_size=65536